# This is a basic workflow to help you get started with Actions

name: Angular-Deploy-Prod

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and npm run build
        working-directory: /home/runner/work/Platform/Platform/CyberRange/CyberRangeAngular/
        run: |
          npm i
          npm run build:ci
      - name: Deploy to dev-server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: /home/runner/work/Platform/Platform/CyberRange/CyberRangeAngular/dist/
          remote: /var/www/Cyberrange/Angular
          #remote: ${{ secrets.REMOTE_TARGET }} 
          host: ${{ secrets.PRODHOST }}
          username: ${{ secrets.PRODUSER }}
          password: ${{ secrets.PRODPASS }}

      - name: Restart web-dev service
        uses: garygrossgarten/github-action-ssh@v0.5.0
        with:
          command: echo ${{ secrets.PRODPASS }} | sudo -S service kestrel-Cyberrange-test restart
          host: ${{ secrets.PRODHOST }}
          username: ${{ secrets.PRODUSER }}
          password: ${{ secrets.PRODPASS }}
