name: DotNet-Build

on:
  push:
    branches: [ mainXXX ]
  pull_request:
    branches: [ mainXXX ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
  
    - name: Dotnet publish
      run: dotnet publish CyberRange/CyberRange.sln -c Release -o build
