name: DotNet-Deploy-Prod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: edit connection string
      uses: benday-inc/edit-dbconnstr-in-appsettings@main
      with:
        pathtosettingsfile: '${{ github.workspace }}/CyberRange/CyberRangeProject/appsettings.json'
        name: "DefaultConnection"
        connectionstring: ${{ secrets.DEFAULTCONNECTION }}
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
  
    - name: Dotnet publish
      run: dotnet publish CyberRange/CyberRange.sln -c Release -o build
      
    - name: Deploy to dev-server
      uses: garygrossgarten/github-action-scp@release
      with:
        local: /home/runner/work/Platform/Platform/build/
        remote: /var/www/Cyberrange/DotNet
        #remote: ${{ secrets.REMOTE_TARGET }} 
        host: ${{ secrets.PRODHOST }}
        username: ${{ secrets.PRODUSER }}
        password: ${{ secrets.PRODPASS }}

    - name: Restart web-dev service
      uses: garygrossgarten/github-action-ssh@v0.5.0
      with:
        command: echo ${{ secrets.PRODPASS }} | sudo -S service kestrel-Cyberrange-test restart
        host: ${{ secrets.PRODHOST }}
        username: ${{ secrets.PRODUSER }}
        password: ${{ secrets.PRODPASS }}
